name: "Frizbee Action"
description: "Automatically correct GitHub Actions and container image tags to digests"
author: "Stacklok, Inc."
branding:
  icon: "at-sign"
  color: "green"
inputs:
  actions:
    description: "Actions to correct"
    required: false
    default: ""
  action_paths:
    description: "Paths to search for actions"
    required: false
    default: ""
  dockerfiles:
    description: "Dockerfiles to correct"
    required: false
    default: '["Dockerfile"]'
  kubernetes:
    description: "Kubernetes manifests to correct"
    required: false
    default: ""
  docker_compose:
    description: "Docker Compose files to correct"
    required: false
    default: ""
  open_pr:
    description: "Open a PR with the changes"
    required: false
    default: "true"
  fail_on_unpinned:
    description: "Fail if an unpinned action/image is found"
    required: false
    default: "false"
  repo_root:
    description: "Operate on files in the specified filesystem location. If unspecified, check out files from the current repo."
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.recursive }}
