name: "Frizbee Action"
description: "Automatically correct GitHub Actions and container image tags to digests"
author: "Stacklok, Inc."
branding:
  icon: "at-sign"
  color: "green"
inputs:
  actions:
    description: "Actions to correct"
    required: false
    default: '[".github/workflows"]'
  dockerfiles:
    description: "Dockerfiles to correct"
    required: false
    default: '["Dockerfile"]'
  kubernetes:
    description: "Kubernetes manifests to correct"
    required: false
    default: ""
  docker_compose:
    description: "Docker Compose files to correct"
    required: false
    default: ""
  open_pr:
    description: "Open a PR with the changes"
    required: false
    default: "true"
  fail_on_unpinned:
    description: "Fail if an unpinned action/image is found"
    required: false
    default: "false"
  in_place:
    description: "Update the files in place"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.recursive }}
